### PR TITLE
Long wait output issue has been fixed

### PR DESCRIPTION
**Pull request by muhammad-asad-confiz**
There was an issue with write method. It takes too much time while printing long output like node. A new method has been added to resolve this issue.

### CODE REVIEW

**Comment by sureshg** [comment]
IMHO, we should move to a more proper exec library (like https://github.com/zeroturnaround/zt-exec) which handle this for us. By the way, how much slow down we are seeing earlier? With the data we have, I don't expect any significant difference between the `write(int b)` and `write([]b...)` methods, other than the former method generate a bunch of garbages.

**Comment by muhammad-asad-confiz** [comment]
Hi Suresh,
Previously it was taking more than an hour to print the workorder to the logger but now it's been printed in no time. I have tested it on my local environment. If we can push this to one of dev inductor then we can benchmark it.
If we want to integrate https://github.com/zeroturnaround/zt-exec then can we have a discussion on this.

**Comment by muhammad-asad-confiz** [comment]
Hi Suresh,

I have implemented the zt-exec (https://github.com/zeroturnaround/zt-exec) library in the inductor but the problem which I am facing right now is that this library returns the whole workorder or any other long/short output as a single line. When we pass that line to our output handler our output handler is not able to process it as we were expecting, like in case of workorder, the whole workorder is not printed because the workorder has PRIVARE KEY and we have a logic that a line contains PRIVATE KEY we do not print that line.

**Comment by gauravlall** [comment]
Lets not print the whole workorder

**Pull request closed without merging**
