### PR TITLE
Forcing to use init type instead of systemd

### PR DESCRIPTION
**Pull request by msumankumar**

### CODE REVIEW

**Review by dschelchkov — COMMENTED** [review]
Has this been tested on Ubuntu and Windows platforms?

**Comment by msumankumar** [comment]
@dschelchkov Added condition to run only for the rhel. Can you please review and merge it?

**Comment by mosabua** [comment]
CLA is okay. @msumankumar will reconfig his git install to correct user for future. I can confirm that he is part of OO team and covered in terms of CLA..

**Comment by msumankumar** [comment]
Closing this request as its merged here https://github.com/oneops/oneops/pull/441

**Pull request closed without merging**
